### ISSUE TITLE
AdjustTheFov

### ISSUE THREAD

**Issue by ImportTaste** [techiew/EldenRingMods#3]
I've noticed a new chunk of code added to AdjustTheFov. If I were to compile it, would it be functional? Or is it not ready for even preliminary tests yet?

**Comment by techiew** [comment]
It doesn't work. This particular patch requires a code cave or a hook and I'm trying to find a nice solution for it.

**Comment by techiew** [comment]
Released it now: https://www.nexusmods.com/eldenring/mods/325
