### ISSUE TITLE
Disabling camera recentering on lock-on if no target is in range

### ISSUE THREAD

**Issue by ImportTaste** [techiew/EldenRingMods#5]
EldenRingFpsUnlockAndMore recently released a new version that has a new feature: "added option to disable camera reset on lock-on if no target is in range"

Here's the relevant code:

https://github.com/uberhalit/EldenRingFpsUnlockAndMore/commit/1c0104c6229b207ec09e13cb90951831413d4eab#diff-088a6f733776c1bfb44c467422e95027909604dc885e12642faa6d49ebf8137fR147-R161

**Comment by techiew** [comment]
Sweet, I'll make a .dll for that one too.

**Comment by techiew** [comment]
Added this in 2a756a9475bdd7cbbc575cd1853c49805ead1404
