### ISSUE TITLE
SkipTheIntro.dll triggers Defender (Anti-Vir)

### ISSUE THREAD

**Issue by MisterGoodcat** [techiew/EldenRingMods#8]
The current download from Nexus Mods (SkipTheIntro-421-2-2-1650404835.zip) triggers a PUS-warning with Microsoft Defender:

![image](https://user-images.githubusercontent.com/7507932/164184986-d349f305-cdd4-4f8c-a9d5-3551155c61ff.png)

It detects Win32/Uwamson.A!ml

Seems like it already has been [posted to Virus Total](https://www.virustotal.com/gui/file/76b5ad744c19d47643bfec092d6b451ca4a8134a4a2090e7d4772a3c895c10b5) and returns as (false) positive for a few other engines there too.

**Comment by techiew** [comment]
Not sure if I can control what antiviruses think of my DLLs, it seems pretty random.

**Comment by Aemony** [comment]
`!ml` indicates the virus definition was created using machine learning, which is semi-prone to false positives.

As for having control, what you can always do is report it as a false positive which will allow the AV vendor to remove the detection and better train the machine learning algorithm: https://www.microsoft.com/en-us/wdsi/filesubmission/

**Comment by techiew** [comment]
Thank you, I reported it.
